spring.application.name=Lunch_TG_BOT

# Telegram Bot Configuration
telegram.bot.bot-token=8696152294:AAFwN7Kk3KWawvsuJL7EFMY43kAykpady1Q
telegram.bot.bot-username=lunch_helper_v2_bot
telegram.bot.chat-id=7848676630
telegram.bot.reminder-interval-minutes=30
telegram.bot.lunch-time=12:00
telegram.bot.final-list-time=11:30

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/lunch_bot
spring.datasource.username=postgres
spring.datasource.password=131108
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Server Configuration
server.port=8081

# Logging
logging.level.com.example.lunch_tg_bot=DEBUG
logging.level.org.springframework.scheduling=DEBUG
logging.level.org.telegram=DEBUG
